<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ASV0EV8" failures="4" tests="20" name="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" time="237.880" errors="0" timestamp="2021-09-17T12:13:37 IST" skipped="16">
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="12.136">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData.createOrganizationWithMultipleData(CreateOrganizationWithMultipleData.java:37)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.358">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.591">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData.createOrganizationWithMultipleData(CreateOrganizationWithMultipleData.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="12.976">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.368">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="12.332">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="12.326">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.787">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.504">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData.createOrganizationWithMultipleData(CreateOrganizationWithMultipleData.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="12.467">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.797">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.248">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.913">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.578">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="12.419">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.779">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData.createOrganizationWithMultipleData(CreateOrganizationWithMultipleData.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.753">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.658">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.957">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
  <testcase classname="com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData" name="createOrganizationWithMultipleData" time="11.933">
    <skipped/>
  </testcase> <!-- createOrganizationWithMultipleData -->
  <system-out/>
</testsuite> <!-- com.crm.SeleniumProject_Maven.Script.CreateOrganizationWithMultipleData -->
